[package]
name = "batch_downloader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.32.0", features = ["full"] }
futures-core = "0.3.28"

tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"]}
tower-http = { version = "0.4.4", features = ["trace"] }

once_cell = "1.18.0"

axum = "0.6.20"
axum-prometheus = "0.4.0"

serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"

moka = { version = "0.12.0", features = ["future"] }

md5 = "0.7.0"

smallvec = { version = "1.11.1", features = ["serde"] }
smartstring = { version = "1.0.1", features = ["serde"] }
reqwest = { version = "0.11.20", features = ["json", "stream", "multipart"] }

bytes = "1.5.0"
tempfile = "3.8.0"
zip = "0.6.6"

base64 = "0.21.4"

minio-rsc = "0.2.0"
async-stream = "0.3.5"

translit = "0.5.0"

sentry = { version = "0.31.7", features = ["debug-images"] }
