[package]
name = "batch_downloader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.37.0", features = ["full"] }
tokio-util = { version = "0.7.10", features = ["compat", "io"] }
futures-core = "0.3.30"
futures-util = "0.3.30"

tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"]}
sentry-tracing = "0.32.3"
tower-http = { version = "0.5.2", features = ["trace"] }

once_cell = "1.19.0"

axum = { version = "0.7.5", features = ["multipart"] }
axum-prometheus = "0.6.1"

serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"

moka = { version = "0.12.7", features = ["future"] }

md5 = "0.7.0"

smallvec = { version = "1.13.2", features = ["serde"] }
smartstring = { version = "1.0.1", features = ["serde"] }
reqwest = { version = "0.12.4", features = ["json", "stream", "multipart"] }

bytes = "1.6.0"
tempfile = "3.10.1"
zip = "1.1.1"

base64 = "0.22.0"

async-stream = "0.3.5"

translit = "0.5.0"

sentry = { version = "0.32.3", features = ["debug-images"] }

chrono = "0.4.38"
