[package]
name = "batch_downloader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.35.0", features = ["full"] }
futures-core = "0.3.29"

tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"]}
tower-http = { version = "0.5.0", features = ["trace"] }

once_cell = "1.19.0"

axum = "0.7.2"
axum-prometheus = "0.5.0"

serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"

moka = { version = "0.12.1", features = ["future"] }

md5 = "0.7.0"

smallvec = { version = "1.11.2", features = ["serde"] }
smartstring = { version = "1.0.1", features = ["serde"] }
reqwest = { version = "0.11.22", features = ["json", "stream", "multipart"] }

bytes = "1.5.0"
tempfile = "3.8.1"
zip = "0.6.6"

base64 = "0.21.5"

minio-rsc = "0.2.0"
async-stream = "0.3.5"

translit = "0.5.0"

sentry = { version = "0.32.0", features = ["debug-images"] }

tokio-cron-scheduler = "0.9.4"

chrono = "0.4.31"
